# This is the inventory file for the NUC lab.
# It defines which machines Ansible will manage.

[nucs]
# The 'nucs' group contains all the lab machines. For now, only one is listed.
# The format is: <hostname> <variable=value>
nuc01.lab.local ansible_host=192.168.1.152 ansible_user=test