# This is the inventory file for the NUC lab.
# It defines which machines Ansible will manage.

# NUCs that have been set up and have the csadmin/student accounts.
[configured_nucs]
nuc01.lab.local ansible_host=192.168.1.152
nuc02.lab.local ansible_host=192.168.1.203
nuc03.lab.local ansible_host=192.168.1.131
nuc04.lab.local ansible_host=192.168.1.211
nuc05.lab.local ansible_host=192.168.1.237
nuc06.lab.local ansible_host=192.168.1.204
nuc07.lab.local ansible_host=192.168.1.114
nuc08.lab.local ansible_host=192.168.1.230
nuc09.lab.local ansible_host=192.168.1.240
nuc10.lab.local ansible_host=192.168.1.231
nuc11.lab.local ansible_host=192.168.1.236


# NUCs that are fresh and only have the 'test' account.
[new_nucs]
nuc12.lab.local ansible_host=192.168.1.223
