# This is the inventory file for the NUC lab.
# It defines which machines Ansible will manage.

# NUCs that have been set up and have the csadmin/student accounts.
[configured_nucs]
nuc01.lab.local ansible_host=192.168.1.152
nuc02.lab.local ansible_host=192.168.1.203
nuc03.lab.local ansible_host=192.168.1.131

# NUCs that are fresh and only have the 'test' account.
[new_nucs]
nuc04.lab.local ansible_host=192.168.1.211
nuc05.lab.local ansible_host=192.168.1.237
nuc06.lab.local ansible_host=192.168.1.204